{application,redis,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{redis_app,[]}},
              {env,[]},
              {modules,[bench,frog_ets,frog_pond,nsync_callback,redis_app,
                        redis_bench,redis_db,redis_sup]}]}.
